### ISSUE TITLE
cmsis-os2 priorities issue with the FreeRTOS 

### ISSUE THREAD

**Issue by rahmanih** [ARM-software/CMSIS-FreeRTOS#11]
Hi,
the cmsis-os2.h defines priorities going from:
`osPriorityNone          =  0,         ///< No priority (not initialized).`
to
` osPriorityISR           = 56,         ///< Reserved for ISR deferred thread.`

FreeRTOS, however, is customising the priorities using the `configMAX_PRIORITIES` that **can't** be set 
higher than 32, otherwise a compile error occurs, in `portmarco.h` files.
 Added to that, when a thread is created with a priority higher than `configMAX_PRIORITIES` FreeRTOS is lowering it to: `configMAX_PRIORITIES - 1` (check the file tasks.c).

This makes applications misbehave  when using multiple threads with different "cmsis-os" priorities that are higher than `configMAX_PRIORITIES`.

regards
Haithem.

**Comment by rahmanih** [comment]
Hi,

did anybody look at this issue?

regards
Haithem.

**Comment by ReinhardKeil** [comment]
We have looked at it already, but a solution to the problem will be provided after the Easter break.

**Comment by rahmanih** [comment]
> We have looked at it already, but a solution to the problem will be provided after the Easter break.
O.K.! thanks.

regards
Haithem.

**Comment by rahmanih** [comment]
Hi Jonatan,

Can't this issue be considered as a **bug** rather than **enhancement**? 
As aforementioned, when creating cmsis_os threads with different priorities but **greater** than the `configMAX_PRIORITIES`, FreeRTOS will create tasks _**with same**_ priorities which impacts the application behaviour.

regards
Haithem.

**Comment by VladimirUmek** [comment]
Hi rahmanih,

to overcome this limitation of FreeRTOS, RTOS2 API wrapper (cmsis_os2) is not using port optimised task selection. There is a little performance drawback, but on the other hand, there is no need to limit the RTOS2 API.
Please note, that FreeRTOSConfig.h configuration files that come with CMSIS-FreeRTOS RTOS2 examples contain:
```
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 0
#define configMAX_PRIORITIES                    56
```
Thus all user configurable priorities in CMSIS RTOS2 can be used, from osPriorityLow to osPriorityRealtime7.

**Comment by rahmanih** [comment]
great!
closing this as answered.

thanks
Haithem.

**Comment by joeytian** [comment]
Since there is an array's size determined by configMAX_PRIORITIES in FreeRTOS task.c. 

`PRIVILEGED_DATA static List_t pxReadyTasksLists[ configMAX_PRIORITIES ]`

Using CMSIS RTOS 2 with configMAX_PRIORITIES fixed to 56 will increase RAM usage.  Every priority takes ~20 bytes. This is not good for small RAM micro controllers such as some 4KB Cortex-M0 chips.
