### ISSUE TITLE
update against new FreeRTOS v10.1.0

### ISSUE THREAD

**Issue by rahmanih** [ARM-software/CMSIS-FreeRTOS#16]
Hi,

is it possible to update the CMSIS-FreeRTOS against the lastest FreeRTOS release?

regards
Haithem.

**Comment by JonatanAntoni** [comment]
Hi Haithem,

Yes, of course. Is it feasible for you to update all the FreeRTOS files and raise a pull-request? That would help us to speed the things up.

Cheers,
Jonatan

**Comment by VladimirUmek** [comment]
Hi Haithem,

develop branch was recently updated to FreeRTOS V10.1.1. Some debug documentation still needs update, but everything else is ready to use!
