### ISSUE TITLE
Add support to FreeRTOS 10.2.0/CM33

### ISSUE THREAD

**Issue by rahmanih** [ARM-software/CMSIS-FreeRTOS#21]
[FreeRTOS 10.2.0](https://www.freertos.org/) is out with support for  ARMv8-M. 
Could you please consider updating the CMSIS-FreeRTOS against it?

regard
Haithem.

**Comment by VladimirUmek** [comment]
Hi Haithem,

we will review the latest FreeRTOS release and update CMSIS-FreeRTOS accordingly.

**Comment by VladimirUmek** [comment]
CMSIS-FreeRTOS was updated to the latest FreeRTOS version and pack was released.

I'm closing this issue - please open separate issues to track any discovered problems.
