### ISSUE TITLE
why the osTimerxxx is controlled in #if (osCMSIS < 0x20000U)

### ISSUE THREAD

**Issue by swordligit** [ARM-software/CMSIS-FreeRTOS#23]
In the cmsis_os.h,
osTimerStart, osTimerStop, osTimerDelete are declared in the 
#if (osCMSIS < 0x20000U)
osTimerxxx
#endif

Will that means I can only use these API in the less than the cmsis OS2? but the cmsis OS2 does have these APIs, a little confused.

https://arm-software.github.io/CMSIS_5/RTOS2/html/rtos_api2.html

**Comment by VladimirUmek** [comment]
Hi,

I think you are looking at the cmsis_os.h header not cmsis_os2.h.

Header cmsis_os.h and implementation cmsis_os1.c are provided for compatibility with the old RTOS API. 

New, RTOS2 API can be found in cmsis_os2.h file and this is the header file for API you were referencing with the link. If can be found in CMSIS pack (see https://github.com/ARM-software/CMSIS_5/releases or development branch).
RTOS2 wrapper for FreeRTOS is implemented in cmsis_os2.c.

**Comment by swordligit** [comment]
Got it,  need get cmsis_os2.h from the cmsis_5 website.
Thank you a lot.

I still have some problems, with OS1 API timer API. e.g.

osStatus   osTimerStart (osTimerId timer_id, uint32_t timeout) 

And it is declared in the cmsis_os.h,  there is no definition in the cmsis_os1.c, 
it is a defined in the cmsis_os2.c, but the return type is not matched

 osStatus_t osTimerStart (osTimerId_t timer_id, uint32_t ticks) 

how to resolve this problem if I use os1 API? just rename 
osStatus_t to osStatus simply?

**Comment by VladimirUmek** [comment]
Yes (since the underlying type is the same). RTOS2 inherited some functionality from RTOS1 and therefore compatibility modules are designed to use RTOS2 API directly where possible.

Just as a side note - in general I would recommend to use RTOS2 API unless you have to maintain some old software, as thing will be more clean.

**Comment by swordligit** [comment]
Ok, better to upgrade my old software.Thanks a lot!
