### ISSUE TITLE
osPoolDef compile errors.

### ISSUE THREAD

**Issue by swordligit** [ARM-software/CMSIS-FreeRTOS#25]
#define osPoolDef(name, no, type) \
const osPoolDef_t os_pool_def_##name = \
{ (no), sizeof(type), NULL }

should be 
#define osPoolDef(name, no, type) \
const osPoolDef_t os_pool_def_##name = \
{ (no), sizeof(type), **{NULL}** }

because osMemoryPoolAttr_t   is a structure.

**Comment by VladimirUmek** [comment]
Fixed the error, although compiler error should never appear since feature is not enabled.
