### ISSUE TITLE
Is there plan for implement memory pool functions?

### ISSUE THREAD

**Issue by swordligit** [ARM-software/CMSIS-FreeRTOS#26]

**Comment by VladimirUmek** [comment]
Hi,
it would be good to have them implemented eventually but it is not scheduled. Unfortunately there is no proper native support for memory pools in FreeRTOS otherwise this would be already done.
Memory pool functions are something that we could consider implementing in the future.

**Comment by swordligit** [comment]
Is it possible to port the RTX's pool implementation? Anyway, thanks for your information.
