### ISSUE TITLE
The ARM cortex M4 MPU port issues

### ISSUE THREAD

**Issue by swordligit** [ARM-software/CMSIS-FreeRTOS#28]

**Comment by swordligit** [comment]
The MPU port define some special segment, such as privileged_functions, privileged_data, etc. is there example or demo how to define these sections?

**Comment by swordligit** [comment]
Have checked the "FreeRTOS/Demo/CORTEX_MPU_Simulator_Keil_GCC/GCC_Specific", there is a ld script that define the sections privileged_functions and privileged_data.
As for privileged_data, who will copy the data from flash to RAM?

**Comment by JonatanAntoni** [comment]
Hi @swordligit,

As far as I am aware of there are no provisions for loading data from flash to RAM in the GCC libraries. We have this "scatter loading" as part of the device startup components in CMSIS, e.g. in

https://github.com/ARM-software/CMSIS_5/blob/db1dc63b57abf8b7719064e5c034615c97212179/Device/ARM/ARMCM3/Source/GCC/startup_ARMCM3.c#L165-L183 

Cheers,
Jonatan

**Comment by swordligit** [comment]
Thanks a lot! I will check it.
