### ISSUE TITLE
Validation passed?

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS-FreeRTOS#30]
Did this project fully passed the CMSIS RTOS validation suite?

**Comment by VladimirUmek** [comment]
Not fully, but it passes within limitations, see https://arm-software.github.io/CMSIS-FreeRTOS/General/html/tech_data.html#td_limitations
Unfortunately FreeRTOS does not support all CMSIS-RTOS2 API features so we accepted some compromises, and therefore validation suite configuration excludes tests that validate unsupported features.

**Comment by ilg-ul** [comment]
Ok, thank you, quite a lot of limitations.
