### ISSUE TITLE
osThreadGetStackSpace() returns words instead of bytes

### ISSUE THREAD

**Issue by aport** [ARM-software/CMSIS-FreeRTOS#32]
The documentation for `osThreadGetStackSpace()` states that it returns the remaining stack space in bytes. The implementation uses `uxTaskGetStackHighWaterMark()` which returns the number of words.

The result should be multiplied by `sizeof(StackType_t)` to return the number of bytes

**Comment by VladimirUmek** [comment]
Thanks for pointing that out! The commit referenced above should fix that.
