### ISSUE TITLE
Upgrade FreeRTOS Version!

### ISSUE THREAD

**Issue by MohammedMaarof** [ARM-software/CMSIS-FreeRTOS#57]
You need to update FreeRTOS repository to FreeRTOS V10.4.x Because starting from this version each task has a [user definable array of task notifications](https://www.freertos.org/a00110.html#configTASK_NOTIFICATION_ARRAY_ENTRIES).

**Comment by VladimirUmek** [comment]
Hi,
this repository is currently based on FreeRTOS 10.4.6 ([see here](https://github.com/ARM-software/CMSIS-FreeRTOS/blob/b3cc689f417b2aff506a75ac15bfe4dbbecfaa50/Source/include/task.h#L56)).

CMSIS-RTOS2 wrapper implementation does not require using an array of task notifications and therefore define configTASK_NOTIFICATION_ARRAY_ENTRIES is not used (backward compatibility rule applies in such case).
