### ISSUE TITLE
Update the CMSIS-FreeRTOS against the FreeRTOS-Kernel 10.5.0 release.

### ISSUE THREAD

**Issue by rahmanih** [ARM-software/CMSIS-FreeRTOS#58]
Hi,
FreeRTOS [10.5.0](https://github.com/FreeRTOS/FreeRTOS-Kernel/releases) is available.
Could you please consider updating the CMSIS-FreeRTOS against this version.

thanks & regards
Haithem.

**Comment by VladimirUmek** [comment]
Hi, we'll take a look and update the repo. Thanks for the reminder ;)

**Comment by escherstair** [comment]
I've already mentioned in #56, but it's the FreeRTOS-Kernel that has ben updated to release 10.5.0.
'Classic' FreeRTOS itself uses a different release [naming convention](https://github.com/FreeRTOS/FreeRTOS/releases/tag/202112.00).

**Comment by VladimirUmek** [comment]
CMSIS-FreeRTOS is now updated and primary source has been changed from 'Classic' FreeRTOS to [FreeRTOS-Kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel/releases).
Pack will be validated and I expect to be released in the next days (in case no serious issues will be found).

**Comment by VladimirUmek** [comment]
Pack was released today, hence closing the issue.
