### ISSUE TITLE
support for none-arm processors

### ISSUE THREAD

**Issue by donnieran** [ARM-software/CMSIS-FreeRTOS#6]
Is it only suitable for ARM core processor?  I mean if I want use it on a power architecture MCU, is there any problem?

**Comment by VladimirUmek** [comment]
FreeRTOS core is supported on platforms listed on the page http://www.freertos.org/RTOS_ports.html

CMSIS RTOS2 wrapper which uses FreeRTOS is tailored for ARM architecture, but users are free to adopt it for other architectures.

**Comment by JonatanAntoni** [comment]
I guess this question was answered completely thus I close the issue. Please feel free to reopen the issue and continue commenting here if you have any further concerns.
