### ISSUE TITLE
osThreadGetPriority API can not return caller priority

### ISSUE THREAD

**Issue by leodicarpaccio** [ARM-software/CMSIS-FreeRTOS#68]
Hello,

Unfortunately, with current implementation of osThreadGetPriority API, it's impossible to get current priority of calling task because thread_id input parameter can not be NULL.
It's a shame because internal call of freeRTOS API (uxTaskPriorityGet) support this feature.
Could it be corrected ?

Thanks

**Comment by leodicarpaccio** [comment]
Hi,

Ok it make sense. Sorry for disturbance, I should have searched deeper. 
Regards

**Comment by VladimirUmek** [comment]
No worries ;)
