### ISSUE TITLE
osThreadResume does not resume blocked thread

### ISSUE THREAD

**Issue by futurezeb** [ARM-software/CMSIS-FreeRTOS#69]
FreeRTOS Kernel 10.4.3 LTS Patch 3
CMSIS-FreeRTOS v 10.5.1

# Expected Behavior
The function should unblock any thread, **regardless of why the thread was blocked.**

The documentation of [osThreadResume](https://www.keil.com/pack/doc/CMSIS/RTOS/html/group__CMSIS__RTOS__ThreadMgmt.html#ga3dbad90eff394b02de76a452c84c5d80) states that 
> The thread becomes ready regardless of the reason why the thread was blocked.

# Actual Behavior
The thread is still in `BLOCKED` state after calling `osThreadResume()` when thread was not blocked by `osThreadSuspend()`.

# Reason
`osThreadResume()` calls `vTaskResume()`, which checks `prvTaskIsTaskSuspended()`.
`prvTaskIsTaskSuspended()` **only** returns true when the thread was suspended using `osThreadSuspend()`.

From FreeRTOS - `tasks.c:1836`
> /* Is it in the suspended list because it is in the Suspended
                 * state, or because is is blocked with no timeout? */
                if( listIS_CONTAINED_WITHIN( NULL, &( pxTCB->xEventListItem ) ) != pdFALSE )

# Solution
The FreeRTOS function `xTaskAbortDelay()` must be used instead so that the implementation is correct according to the documentation linked above.

**Comment by VladimirUmek** [comment]
Hi,

many thanks for a nice explanation and proposed solution! The fix for this problem was now finally implemented and pushed into main repo branch.
