### ISSUE TITLE
[Update]: FreeRTOS 10.6.x releases available

### ISSUE THREAD

**Issue by rahmanih** [ARM-software/CMSIS-FreeRTOS#78]
Hi,

the [FreeRTOS 10.6.0/10.6.1](https://github.com/FreeRTOS/FreeRTOS-Kernel/releases)  releases are available.

regards
Haithem.

**Comment by VladimirUmek** [comment]
We are working on update ;)

**Comment by rahmanih** [comment]
> We are working on update ;)

proactive as usual like it!, just to get my ticket mentioned in the git changelog 😀
