### ISSUE TITLE
NO cmsis_os2.h

### ISSUE THREAD

**Issue by abcamus** [ARM-software/CMSIS-FreeRTOS#8]
cannot find "cmsis_os2.h" that included in some source files

**Comment by JonatanAntoni** [comment]
Hi @abcamus,

CMSIS-FreeRTOS provides only the wrapper implementation of CMSIS-RTOS2 API for FreeRTOS. The CMSIS-RTOS2 API (cmsis_os2.h) itself is declared by [CMSIS](https://github.com/ARM-software/CMSIS_5).  

The header file you are looking for is here: https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/RTOS2/Include/cmsis_os2.h.

Cheers,
Jonatan
